version: '3'

tasks:
  install:
    cmds:
    - go mod download
  lint:
    cmds:
    - go run . .
  format:
    cmds:
    - gofmt -w .
  test:
    cmds:
    - go test ./rules/...
  coverage:
    cmds:
    - go test -coverprofile=coverage.out ./rules/...
  documentation:
    cmds:
    - rm -rf build/doc2go/
    - doc2go -out build/doc2go/ ./rules/...
