name: code-analysis

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HADOLINT_PATH: /usr/local/bin/hadolint

jobs:
  run-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-workspace

      - uses: jwlawson/actions-setup-cmake@v2

      - run: |
          sudo apt-get install -y \
            just libboost-program-options-dev libxml2-utils
          sudo wget -qO "$HADOLINT_PATH" \
            https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod a+x "$HADOLINT_PATH"

      - run: |
          just prepare
          just build

      - run: |
          just lint
          uv run poe lint
          pnpm lint

  upload-coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-workspace

      - run: pnpm -r coverage

      - if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
