name: code-analysis

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HADOLINT_PATH: /usr/local/bin/hadolint

jobs:
  run-lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/actions/setup-workspace

    - run: |
        sudo apt-get install -y chktex libxml2-utils
        go install github.com/checkmake/checkmake/cmd/checkmake@latest
        go install github.com/terraform-linters/tflint@latest
        sudo wget -qO "$HADOLINT_PATH" \
          https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        sudo chmod a+x "$HADOLINT_PATH"

    - run: just offline-lint

  upload-coverage:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/actions/setup-workspace

    - run: just cov

    - if: github.ref == 'refs/heads/main'
      uses: codecov/codecov-action@v7
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
